name: Patenplugin
version: '${project.version}'
main: me.marc3308.patenplugin.Patenplugin
api-version: 1.19
authors: [Marc3308]
description: Unser Partner Paten System

commands:
  patenwatch:
    description: You can watch the parten like a big boy
    permission: juniorparte
  patentp:
    permission: parte
    description: Teleportiert einen Paten zu einem einzuweisenden Spieler
  patenlog:
    description: lets you search the auditlog
  changename:
    permission: parte
    description: chanches the name of your einweißer
  nichtstören:
    permission: parte
    description: do not desturb and dont get shown fpr the parten

permissions:
  juniorparte:
    description: Du kannst zugucken
  parte:
    description: Du hilfst den neuen Spielern sich zurecht zu finden
  parteleitung:
    description: Du kannst nun auch spezien einfach vergeben
